// <auto-generated />
using System;
using AppAsisten.BD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppAsisten.BD.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AppAsisten.BD.Data.Entity.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("AppAsisten.BD.Data.Entity.Asistencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Entrada")
                        .HasColumnType("datetime2");

                    b.Property<int>("MiembroId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Salida")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("MiembroId");

                    b.ToTable("Asistencias");
                });

            modelBuilder.Entity("AppAsisten.BD.Data.Entity.Cuota", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<bool>("EsPagada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("MiembroId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.HasIndex("MiembroId");

                    b.ToTable("Cuotas");
                });

            modelBuilder.Entity("AppAsisten.BD.Data.Entity.Miembro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsActivo")
                        .HasMaxLength(100)
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("AdministradorId");

                    b.ToTable("Miembros");
                });

            modelBuilder.Entity("AppAsisten.BD.Data.Entity.Asistencia", b =>
                {
                    b.HasOne("AppAsisten.BD.Data.Entity.Administrador", null)
                        .WithMany("Asistencias")
                        .HasForeignKey("AdministradorId");

                    b.HasOne("AppAsisten.BD.Data.Entity.Miembro", "Miembro")
                        .WithMany("Asistencias")
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("AppAsisten.BD.Data.Entity.Cuota", b =>
                {
                    b.HasOne("AppAsisten.BD.Data.Entity.Administrador", null)
                        .WithMany("Cuotas")
                        .HasForeignKey("AdministradorId");

                    b.HasOne("AppAsisten.BD.Data.Entity.Miembro", "Miembro")
                        .WithMany("Cuotas")
                        .HasForeignKey("MiembroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Miembro");
                });

            modelBuilder.Entity("AppAsisten.BD.Data.Entity.Miembro", b =>
                {
                    b.HasOne("AppAsisten.BD.Data.Entity.Administrador", null)
                        .WithMany("Miembros")
                        .HasForeignKey("AdministradorId");
                });

            modelBuilder.Entity("AppAsisten.BD.Data.Entity.Administrador", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Cuotas");

                    b.Navigation("Miembros");
                });

            modelBuilder.Entity("AppAsisten.BD.Data.Entity.Miembro", b =>
                {
                    b.Navigation("Asistencias");

                    b.Navigation("Cuotas");
                });
#pragma warning restore 612, 618
        }
    }
}
